# --- REQUIRED BASICS ---
title: "Srishti Gupta - 4th year Undergrad at University of Illinois Urbana-Champaign"
description: "hello!!"
url: "https://srishtigupt.github.io"     # your GitHub Pages domain
baseurl: "/CIERA-REU-2025"               # your project repo path
repository: "SrishtiGupt/CIERA-REU-2025"

# --- THEME (do NOT set `theme:` anywhere) ---
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# --- AUTHOR CARD ON THE RIGHT ---
author:
  name: "Srishti Gupta"
  pronouns: "she/her"
  bio: "Hi! I'm Srishti and I'm a senior majoring in physics at the University of Illinois Urbana-Champaign. This summer I had the opportunity to work with Professor Suzan vanderLee on inferring strain of the lithosphere of Mars with recordings of marsquakes from the SEIS mission on the Mars InSight lander. I have many hobbies, but I especially love to do crafts like origami or making friendship bracelets."
  employer: "University of Illinois Urbana-Champaign"
  email: "srishti8@illinois.edu"
  github: "SrishtiGupt"
  linkedin: "https://www.linkedin.com/in/srishti-gupta-18b62124b"
  avatar: "/images/profile.png"          # optional; adjust path or remove

# --- BUILD SETTINGS ---
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

include:
  - _pages

# Make all normal pages use the "single" layout and show the author card
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
